package ru.clevertec.check.exceptions;

public enum ExceptionType {
    READFILEEXCEPTION,
    NOPRODUCTEXCEPTION,
    NODISCOUNTCARDEXCEPTION,
    INSUFFICIENTSTOCKEXCEPTION,
    INCORRECTREQUESTEXCEPTION,
    NOTENOUGHMONEYEXCEPTION,
}
